export const JORGE_ALVAREZ_MAYNEZ = "JORGE ÁLVAREZ MÁYNEZ";
export const CLAUDIA_SHEINBAUM = "CLAUDIA SHEINBAUM";
export const XOCHITL_GALVEZ = "XÓCHITL GÁLVEZ";

export const CLAUDIA_SHEINBAUM_ID = "21044";
export const XOCHITL_GALVEZ_ID = "17523";
export const JORGE_ALVAREZ_MAYNEZ_ID = "130054";
