interface ProgramGroups {
    [groupName: string]: string[];
}
export const programGroupsTv: ProgramGroups = {
    "Grupo Imagen": [
        "Imagen Noticias",
        "Imagen Noticias con Ciro Gómez Leyva",
        "Imagen Noticias con Francisco Zea",
        "Imagen Noticias Fin de Semana",
        "Transmisión Especial Imagen Televisión",
    ],
    "Grupo Milenio": [
        "Asalto a la Razón con Carlos Marín",
        "Meta 24: El Resumen",
        "Milenio Domingo Tarde 13:00 hrs",
        "Milenio Domingo Tarde 14:00 hrs",
        "Milenio Domingo Tarde 15:00 hrs",
        "Milenio Domingo Tarde 16:00 hrs",
        "Milenio Domingo Tarde 17:00 hrs",
        "Milenio Domingo Tarde 18:00 hrs",
        "Milenio Domingo Tarde 19:00 hrs",
        "Milenio Noticias con Alejandro Domínguez",
        "Milenio Noticias Domingo 1ra",
        "Milenio Noticias Domingo 3ra",
        "Milenio Noticias Domingo 4ta.",
        "Milenio Noticias Domingo 5ta.",
        "Milenio Noticias Madrugada",
        "Milenio Noticias Mañana Cuarta",
        "Milenio Noticias Mañana Primera",
        "Milenio Noticias Mañana Quinta",
        "Milenio Noticias Mañana Segunda",
        "Milenio Noticias Mañana Sexta",
        "Milenio Noticias Mañana Tercera",
        "Milenio Noticias Noche 1ra",
        "Milenio Noticias Noche 2da",
        "Milenio Noticias Sábado 3ra",
        "Milenio Noticias Sábado 4ta",
        "Milenio Noticias Sábado 5ta",
        "Milenio Noticias Sábado Primera",
        "Milenio Noticias Sábado Segunda",
        "Milenio Noticias Sábado Tercera",
        "Milenio Noticias Tarde 1ra",
        "Milenio Noticias Tarde 2da",
        "Milenio Noticias Tarde 3da",
        "Milenio Noticias Tarde 4ta",
        "Milenio Noticias Tarde 5ta",
        "Milenio Noticias Tarde 6ta",
        "Milenio Noticias Tarde 7ta",
        "Milenio Sábado Tarde 13:00 hrs.",
        "Milenio Sábado Tarde 14:00 hrs.",
        "Milenio Sábado Tarde 15:00 hrs.",
        "Milenio Sábado Tarde 19:00 hrs.",
        "Transmisión Especial Milenio",
    ],
    Televisa: [
        "A las Tres",
        "Agenda Pública (Domingo)",
        "Alebrijes, Águila o Sol",
        "Despierta",
        "En Punto",
        "Es la Hora de Opinar",
        "Estrictamente Personal",
        "Foro TV Domingo Noche de 21:00 hrs.",
        "Foro TV Domingo Noche de 22:00 hrs.",
        "Hora 21",
        "Hoy",
        "Las Noticias con Carlos Hurtado",
        "Las Noticias de las 11:00 horas",
        "Las Noticias de las 13:00",
        "Las Noticias de las 16:00 hrs.",
        "Las Noticias de las 17:00 hrs.",
        "Las Noticias de las 18:00 hrs.",
        "Las Noticias de las 19:00 hrs.",
        "Las Noticias de las 20:00 hrs.",
        "Las Noticias de las Cinco de la Mañana",
        "Milenio Sábado Tarde 17:00 hrs.",
        "Milenio Sábado Tarde 18:00 hrs.",
        "Noticias 05:50",
        "Noticias MX",
        "Paralelo 23",
        "Sin Filtro",
        "Tercer Grado",
        "Transmisión Especial Foro TV",
    ],
    "TV Azteca": [
        "ADN40.MX Noticias Primera Emisión",
        "ADN Conmigo",
        "ADN Conmigo (Domingo)",
        "ADN Conmigo Fin de Semana",
        "ADN40.MX",
        "Así Amanece",
        "Campaneando",
        "Contra Portada",
        "Coterreando la Noticia",
        "Es Noticia con Hannia Novell",
        "Es Noticia con Jorge Armando Rocha",
        "Es Noticia Domingo",
        "Es tendencia",
        "Es tendencia con Max Espejel - Sábado",
        "Hechos de la Noche",
        "Hechos Domingo",
        "La Entrevista con Sarmiento (Martes)",
        "Noticias a ras de tierra",
        "Noticias para despertar",
        "Noticias para despertar",
        "República MX",
        "Sala de Guerra",
        "Todo Personal",
        "Transmisión Especial ADN 40",
        "Tu Ciudad en Tiempo Real",
    ],
    "Heraldo TV": [
        "Contra Cara",
        "Esta Mañana",
        "Noticias de la Mañana",
        "Noticias de la tarde",
        "Reporte H",
        "República H",
        "Tiempo de negocios",
    ],
    "Bloomberg TV": [
        "Al Cierre",
        "Al Sonar la Campana",
        "El Financiero Bloomberg 20 horas",
        "Financiero Bloomberg de las 17:00",
        "Financiero Bloomberg de las 18:00",
        "Financiero Bloomberg de las 19:00",
        "Ganadores y Perdedores",
    ],
    Latinus: ["Latinus Diario con Claudio Ochoa", "Latinus con Carlos Loret"],
};

export const programGroupsPeriodico: ProgramGroups = {
    "El Universal": ["El Universal"],
    "Reforma": ["Reforma"],
    "La jornada": ["La Jornada"],
    "Milenio": ["Milenio Diario", "Milenio"],
    "Excelsior": ["Excélsior"],
    "El Financiero": ["El Financiero"],
    "El Economista": ["El Economista"],
};

export const programGroupsRadio: ProgramGroups = {
    "Radio Fórmula": [
        "Atando Cabos",
        "Ciro Gómez Leyva por las mañanas",
        "Eduardo Ruiz Healy (Vespertino)",
        "Fórmula Financiera",
        "Fórmula Noticias",
        "Fórmula Noticias con Azucena Uresti",
        "Fórmula Noticias con Juan Becerra (Domingo)",
        "Fórmula noticias con Juan Becerra Acosta",
        "José Cárdenas Informa",
        "Juntos",
        "La Una: El Radio de la República",
        "Las primeras de Anda",
        "Las Princecitas",
        "Leonardo Curzio en Fórmula",
        "López Dóriga",
        "Por la Mañana con Feregrino",
        "Tiempo Real",
        "Todo para la mujer",
        "Transmisión Especial 104.1 FM",
        "Transmisión Especial Fórmula 103.3 FM",
        "MVS Radio",
        "Elecciones 2024 Tú Decides",
        "En Directo con Ana Francisca Vega",
        "Mesa para Todos",
        "Metrópoli",
        "Noticias MVS 1ª Emisión",
        "Noticias MVS 2ª Emisión",
        "Noticias MVS 3ª Emisión",
        "Pamela Cerdeira en MVS",
        "Televisa Radio",
        "Así las Cosas",
        "Así las Cosas 3ra Emisión",
        "Así las cosas PM",
        "Noticias W",
        "Transmisión Especial Los 40 Principales 101.7 FM",
    ],
    "MVS Radio": [
        "Elecciones 2024 Tú Decides",
        "En Directo con Ana Francisca Vega",
        "Mesa para Todos",
        "Metrópoli",
        "Noticias MVS 1ª Emisión",
        "Noticias MVS 2ª Emisión",
        "Noticias MVS 3ª Emisión",
        "Pamela Cerdeira en MVS",
    ],
    "Televisa Radio": [
        "Así las Cosas",
        "Así las Cosas 3ra Emisión",
        "Así las cosas PM",
        "Noticias W",
        "Transmisión Especial Los 40 Principales 101.7 FM",
    ],

    "NRM Comunicaciones": [
        "Amanece",
        "Enfoque Noticias 1ra Emisión",
        "Enfoque Noticias 2da Emisión",
        "Enfoque Noticias 3ra Emisión",
    ],
    "Imagen RADIO": [
        "Análisis Superior",
        "Imagen Empresarial",
        "Imagen Informativa 1ra",
        "Imagen Informativa 1ra Domingo",
        "Imagen Informativa 2da",
        "Imagen Informativa Domingo 15:00 hrs.",
        "Imagen Informativa Sábado Primera Emisión",
        "Más Allá del Titular",
        "Negocios en Imagen",
        "Ya Cierra",
    ],
    "Heraldo Media Group": [
        "A la Una",
        "Bitácora de Negocios",
        "El Dedo en la Llaga",
        "El Heraldo de la Tarde",
        "Informativo El Heraldo Fin de Semana",
        "Nada Más por Convivir con Juan Ignacio Zavala y Julio Patán",
        "Romandía en El Heraldo",
        "Sergio y Lupita en El Heraldo Radio",
        "Solórzano el Referente Informativo",
        "Zona de Noticias",
    ],
    "Grupo Radio Centro": [
        "Aristegui Noticias en 88.1",
        "La Octava Noticias con Carlos Castellanos",
        "La Octava Noticias con Luisa Cantú",
    ],
};

export const getDefaultStats = (): any => {
    return {
        radio: [],
        television: [],
        periodico: []
    };
};
