export interface Registro {
    FECHA: string;
    HORA: string;
    FAMDESCRIPCION: string;
    FESDESCRIPCION: string;
    FNODESCRIPCION: string;
    FNOTIRAJE: string;
    FTECONDUCTOR: string;
    FNOMEDIO: string;
    FNODIASEMISION: string;
    FCADESCRIPCION: string;
    MUNNOMMUNICIPIO: string;
    FREBANDA: string;
    FREFRECUENCIA: string;
    FREHORARIO: string;
    FMECLAVE: string;
    FMEDISTRIBUCION: string;
    FTMDESCRIPCION: string;
    FCLDESCRIPCION: string;
    VACACTOR: string;
    CAPTITULO: string;
    CAPDURACION: string;
    CAPCLAVE: string;
    CAPCM: string;
    CAPFRACCION: string;
    CAPCOSTOCM: string;
    TEXNOMBRE: string;
    QUENOMBRE: string;
    TEVDESCRIPCION: string;
    VACPARTICIPACION: string;
    VACCATEGORIA: string;
    VACTENDENCIA: string;
    VACFODA: string;
    VACSUBTEMAXML: string;
    VACFVALORACION: string;
    USRNOMBRE: string;
    CAADIST8A12: number;
    CAADIST13A17: number;
    CAADIST18A24: number;
    CAADIST25A34: number;
    CAADIST35A44: number;
    CAADIST45A54: number;
    CAADIST55AMAS: number;
    CAADISTALTO: number;
    CAADISTMEDIO: number;
    CAADISTBAJO: number;
    CAADISTHOMBRE: number;
    CAADISTMUJER: number;
    CAABANDA: string;
    CAAFRECUENCIA: string;
    CAAALCANCEREAL: number;
    TOPDESCRIPCION: string;
    PAGINA: string;
    AUTOR: string;
    CAPNOMBRE: string;
    CAPMEDIO: string;
    FPRDESCRIPCION: string;
    FRESIGLAS: string;
    CAPTIPOCOSTO: number;
    CAPTEXTCOMP: string;
    QUERY: string;
    QUERYHIJO: string;
    FMEDESCRIPCION:string;
    ACTOR:string;
    EJEDESCRIPCIONH:string;
    CIMNOMBREARCHIVO:string;
    CATEGORIA:string;
}
